for x = 0, 10 do
    chim.command("edit.insert", "uiae\n")
end
print("lua config")

-- chim.map("insert", "{char}", "buffer.insert_char")
-- chim.map("insert", "{char}", function(c) chim.command("buffer.insert_char", c) end)
-- chim.map("insert", "{Space}", "buffer.insert_char", " ")
-- chim.map("insert", "{Enter}", "buffer.insert_char", "\n")
chim.map("normal", "wa", function() print("printed a from lua") end)
chim.map("normal", "wb", function() print("printed b from lua") end)
chim.map("normal", "ww", function() print("printed w from lua") end)
chim.map("normal", "c", function() chim.command("edit.insert", "c") end)
chim.map("normal", "x", "buffer.delete_right")
chim.map("normal", "u", "buffer.undo")
chim.map("normal", "U", "buffer.redo")
chim.map("normal", "{C-z}", "buffer.undo")
chim.map("normal", "{C-y}", "buffer.redo")
chim.map("command", "w", function(mov) print(mov) end)
-- chim.map("command", "f{mov}", function(mov) print(mov) end)
